# Generated by Django 2.1.1 on 2018-09-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100 characters max.', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.CharField(default=False, max_length=1000)),
            ],
        ),
    ]
